// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintVault.Backend.Data;

#nullable disable

namespace PrintVault.Backend.Migrations
{
    [DbContext(typeof(PrintVaultContext))]
    partial class PrintVaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintVault.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.ModelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrintModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrintModelId");

                    b.ToTable("ModelImages");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.ModelTag", b =>
                {
                    b.Property<int>("PrintModelId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PrintModelId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ModelTags");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FilamentUsedG")
                        .HasColumnType("double precision");

                    b.Property<int>("PlateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PrintModelId")
                        .HasColumnType("integer");

                    b.Property<int>("PrintTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailLargePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailMediumPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailSmallPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrintModelId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfPlates")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalFilamentUsedG")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalPrintTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PrintModels");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.ModelImage", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.PrintModel", "PrintModel")
                        .WithMany("Images")
                        .HasForeignKey("PrintModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintModel");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.ModelTag", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.PrintModel", "PrintModel")
                        .WithMany("ModelTags")
                        .HasForeignKey("PrintModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintVault.Backend.Models.Tag", "Tag")
                        .WithMany("ModelTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintModel");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Plate", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.PrintModel", "PrintModel")
                        .WithMany("Plates")
                        .HasForeignKey("PrintModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintModel");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintModel", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.Category", "Category")
                        .WithMany("PrintModels")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Category", b =>
                {
                    b.Navigation("PrintModels");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ModelTags");

                    b.Navigation("Plates");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Tag", b =>
                {
                    b.Navigation("ModelTags");
                });
#pragma warning restore 612, 618
        }
    }
}
