// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintVault.Backend.Data;

#nullable disable

namespace PrintVault.Backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260221180003_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintVault.Backend.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedFilamentUsedGrams")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("EstimatedPrintTime")
                        .HasColumnType("interval");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("PrinterProfile")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PrintFiles");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintFileTag", b =>
                {
                    b.Property<Guid>("PrintFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("PrintFileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PrintFileTags");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintFile", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.Category", "Category")
                        .WithMany("PrintFiles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintFileTag", b =>
                {
                    b.HasOne("PrintVault.Backend.Models.PrintFile", "PrintFile")
                        .WithMany("PrintFileTags")
                        .HasForeignKey("PrintFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintVault.Backend.Models.Tag", "Tag")
                        .WithMany("PrintFileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintFile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Category", b =>
                {
                    b.Navigation("PrintFiles");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.PrintFile", b =>
                {
                    b.Navigation("PrintFileTags");
                });

            modelBuilder.Entity("PrintVault.Backend.Models.Tag", b =>
                {
                    b.Navigation("PrintFileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
